2022-11-17T00:08:24.1185083-03:00 0HMM893QO71PC:00000013 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T00:09:19.6775908-03:00 0HMM893QO71PE:00000001 [ERR] Erro ao se Cadastrar!The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior. (8b5cc8a1)
2022-11-17T00:10:47.6310771-03:00 0HMM893QO71PG:00000001 [ERR] Erro ao se Cadastrar!The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior. (8b5cc8a1)
2022-11-17T00:11:12.6874756-03:00 0HMM893QO71PH:00000011 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T00:11:45.2345697-03:00 0HMM895PJO5FB:00000001 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T00:13:05.3968254-03:00 0HMM895PJO5FE:00000001 [ERR] Erro ao se Cadastrar!The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior. (8b5cc8a1)
2022-11-17T00:14:36.7922508-03:00 0HMM896Q1DD66:00000001 [ERR] Erro ao se Cadastrar!The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior. (8b5cc8a1)
2022-11-17T00:26:41.6577520-03:00 0HMM896Q1DD6A:00000001 [ERR] Erro ao se Cadastrar!The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior. (8b5cc8a1)
2022-11-17T00:33:40.9513017-03:00 0HMM89HAJOV4R:00000001 [ERR] Erro ao se Cadastrar!The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior. (8b5cc8a1)
2022-11-17T00:45:02.9665932-03:00 0HMM89NMSAVHO:00000011 [ERR] Erro ao se Cadastrar!The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior. (8b5cc8a1)
2022-11-17T00:58:17.7584578-03:00 0HMM89S1JKB63:00000023 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T00:59:05.7019214-03:00 0HMM89S1JKB63:00000055 [ERR] Erro ao se Cadastrar!The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior. (8b5cc8a1)
2022-11-17T01:32:18.1137653-03:00 0HMM8AHNOLUJ5:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
MySql.Data.MySqlClient.MySqlException (0x80004005): The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.
   at MySqlConnector.Core.ServerSession.TryResetConnectionAsync(ConnectionSettings cs, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 475
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 72
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 280
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Killar.Models.UsersService.AddUser(Users newUser) in D:\Workspace\Killar2.0\Models\UsersService.cs:line 18
   at Killar.Controllers.UsersController.RegisterUser(Users newRegisterUser) in D:\Workspace\Killar2.0\Controllers\UsersController.cs:line 29
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-11-17T01:43:00.4783997-03:00 0HMM8AO8TICAT:00000001 [ERR] Erro ao se Cadastrar!The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior. (8b5cc8a1)
2022-11-17T10:38:52.8982054-03:00 0HMM8K41VH2CR:00000033 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Killar.Models.Cryptography.DecryptedText(String encrypted) in D:\Workspace\Killar2.0\Models\Cryptography.cs:line 43
   at AspNetCore.Views_Users_UserProfile.<ExecuteAsync>b__8_0() in D:\Workspace\Killar2.0\Views\Users\UserProfile.cshtml:line 54
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Views_Users_UserProfile.ExecuteAsync() in D:\Workspace\Killar2.0\Views\Users\UserProfile.cshtml:line 4
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-11-17T10:42:47.2142643-03:00 0HMM8K65L02SJ:00000035 [ERR] Erro ao se Cadastrar!String reference not set to an instance of a String. (Parameter 's') (e2b17663)
2022-11-17T10:42:58.8520796-03:00 0HMM8K65L02SJ:00000057 [ERR] Erro ao Realizar Login!String reference not set to an instance of a String. (Parameter 's') (fe66c00d)
2022-11-17T10:43:06.3965487-03:00 0HMM8K65L02SJ:00000067 [ERR] Erro ao Realizar Login!String reference not set to an instance of a String. (Parameter 's') (fe66c00d)
2022-11-17T10:46:21.8144773-03:00 0HMM8K84O20IB:00000021 [ERR] Erro ao se Cadastrar!String reference not set to an instance of a String. (Parameter 's') (e2b17663)
2022-11-17T10:48:08.4476926-03:00 0HMM8K94DGI5H:00000021 [ERR] Erro ao se Cadastrar!String reference not set to an instance of a String. (Parameter 's') (e2b17663)
2022-11-17T10:58:04.0819987-03:00 0HMM8KEPLI11C:00000011 [ERR] Erro ao Realizar Login!Couldn't connect to server (10802214)
2022-11-17T22:05:15.9087232-03:00  [FTL] Unable to start Kestrel. (fc6a528d)
System.IO.IOException: Failed to bind to address http://127.0.0.1:5000: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Normalmente é permitida apenas uma utilização de cada endereço de soquete (protocolo/endereço de rede/porta).
 ---> System.Net.Sockets.SocketException (10048): Normalmente é permitida apenas uma utilização de cada endereço de soquete (protocolo/endereço de rede/porta).
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2022-11-17T22:09:18.1315490-03:00 0HMM905IFO6Q7:00000081 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:14:29.0121259-03:00 0HMM908SN5RVI:00000011 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:14:45.6670870-03:00 0HMM9093JJ8ET:00000001 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:14:54.9509593-03:00 0HMM9096CQCF8:00000001 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:14:59.3439924-03:00 0HMM9096CQCF8:00000011 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:15:04.7713797-03:00 0HMM9096CQCF8:00000021 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:15:16.2262263-03:00 0HMM909CMV8V0:00000001 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:15:28.7548696-03:00 0HMM909GEMGI7:00000001 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:15:32.6776598-03:00 0HMM909GEMGI7:00000011 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:15:38.4223266-03:00 0HMM909GEMGI7:00000021 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:16:22.4548691-03:00 0HMM90A0ESLQS:00000001 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:16:27.4018971-03:00 0HMM90A0ESLQS:00000021 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:16:33.0854648-03:00 0HMM90A0ESLQS:00000031 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:17:55.3030838-03:00 0HMM90AS4S034:00000001 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:18:00.3489854-03:00 0HMM90AS4S034:00000011 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:18:58.4853321-03:00 0HMM90BEUKRBC:00000001 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:19:01.9038849-03:00 0HMM90BEUKRBC:00000011 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:19:06.9466725-03:00 0HMM90BEUKRBC:00000021 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:19:35.5353885-03:00 0HMM90BQ070K8:00000001 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:19:40.2370587-03:00 0HMM90BQ070K8:00000011 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:19:44.8358102-03:00 0HMM90BQ070K8:00000021 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:21:26.0014872-03:00 0HMM90CQTOQ07:00000001 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:22:41.7880984-03:00 0HMM90DHG40CP:00000001 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:23:02.7016463-03:00 0HMM90DHG40CP:00000011 [ERR] Erro ao Realizar Login!Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (6fde2012)
2022-11-17T22:30:47.8587459-03:00 0HMM90HU3A8GH:00000021 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Killar.Controllers.Authentication.CheckLoginAndPassword(String login, String password, Controller controller) in D:\Workspace\Killar2.0\Controllers\Authentication.cs:line 38
   at Killar.Controllers.HomeController.Login(String login, String password, Exception e) in D:\Workspace\Killar2.0\Controllers\HomeController.cs:line 32
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-11-17T22:32:18.7398381-03:00 0HMM90ISGLQRN:00000011 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Killar.Controllers.Authentication.CheckLoginAndPassword(String login, String password, Controller controller) in D:\Workspace\Killar2.0\Controllers\Authentication.cs:line 38
   at Killar.Controllers.HomeController.Login(String login, String password) in D:\Workspace\Killar2.0\Controllers\HomeController.cs:line 32
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-11-17T22:32:45.2098467-03:00 0HMM90J5AN6OD:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Killar.Controllers.Authentication.CheckLoginAndPassword(String login, String password, Controller controller) in D:\Workspace\Killar2.0\Controllers\Authentication.cs:line 38
   at Killar.Controllers.HomeController.Login(String login, String password) in D:\Workspace\Killar2.0\Controllers\HomeController.cs:line 32
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-11-17T22:33:57.6020572-03:00 0HMM90JQTFM8B:00000001 [ERR] Erro ao Realizar Login! (59774930)
2022-11-17T22:34:11.4686938-03:00 0HMM90JQTFM8B:00000011 [ERR] Erro ao Realizar Login! (59774930)
2022-11-17T22:34:16.7423198-03:00 0HMM90JQTFM8B:00000021 [ERR] Erro ao Realizar Login! (59774930)
2022-11-17T22:36:26.4175318-03:00 0HMM90L78BAH2:00000001 [ERR] Erro ao Realizar Login!Exception of type 'System.Exception' was thrown. (0c4cff8c)
2022-11-17T22:36:31.1442424-03:00 0HMM90L78BAH2:00000011 [ERR] Erro ao Realizar Login!Exception of type 'System.Exception' was thrown. (0c4cff8c)
2022-11-17T22:36:36.2568800-03:00 0HMM90L78BAH2:00000021 [ERR] Erro ao Realizar Login!Exception of type 'System.Exception' was thrown. (0c4cff8c)
